# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ExamPreparation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  IntegrationTest:
    runs-on: ubuntu-latest

    steps:
      - name:  checks-out repository
        uses: actions/checkout@v4
      
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
  
      - name: display name
        run: echo PowerCell12
  
      - name: Install packages
        run: npm install

  
      - name: run the unit tests  
        run: npm run test:unit



  UITest:
    needs: IntegrationTest
    runs-on: ubuntu-latest

    steps:
      - name:  checks-out repository
        uses: actions/checkout@v4
      
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
  
      - name: Install packages
        run: npm install &  npx playwright install  

      - name: Start the server
        run: npm start & 
  

      - name: run the ui tests
        run: npm run test:UI
